hide_cursor = true
general {
	hide_cursor = true
	ignore_empty_input = true
}

animations {
	bezier = outBezier, 0.33, 1, 0.68, 1
	bezier = inBezier, 0.32, 0, 0.67, 0

	animation = fadeIn, 1, 25, outBezier
	animation = fadeOut, 1, 25, inBezier
}

background {
	monitor = DP-4
	path = ~/Pictures/lockscreen.png
}

background {
	monitor = HDMI-A-3
	path = ~/Pictures/lockscreen2.jpeg
}

input-field {
	monitor = DP-4
	size = 320, 55
	dots_size = 0.4
	dots_spacing = 0.4
	dots_center = false
	outer_color = rgba(36, 0, 70, 0.85)
	inner_color = rgba(90, 24, 154, 0.35)
	font_color = rgba(224, 170, 255, 0.9)
	position = 800, -500
	bheck_color = rgba(199, 125, 255, 0.5)
	shadow_passes = 5
	shadow_boost = 5.0
	shadow_color = rgb(36, 0, 70)
}

# clock
label {
	monitor = DP-4
	text = $TIME12
	font_size = 150
	font_family = Magic Retro
	color = rgba(224, 170, 255, 0.5)
	position = -650, 500
	shadow_passes = 2
	shadow_boost = 3.0
	shadow_color = rgb(36, 0, 70)
}

#username
label {
	monitor = HDMI-A-3
	text = $USER
	font_size = 100
	font_family = Magic Retro
	color = rgba(224, 170, 255, 0.5)
	position = -550, -400
	shadow_passes = 3
	shadow_boost = 2.0
	shadow_color = rgb(36, 0, 70)
}
