# ANIMATIONS

animations {
	enabled = yes

	bezier = inBezier, 0.33, 1, 0.68, 1
	bezier = outBezier, 0.32, 0, 0.67, 0 
	
	animation = windowsIn, 1, 5, inBezier, slide
	animation = windowsOut, 1, 5, outBezier, slide
	animation = windowsMove, 1, 5, inBezier, slide

	animation = layersIn, 1, 5, inBezier, slide
	animation = layersOut, 1, 5, outBezier, slide

	animation = fadeIn, 1, 5, inBezier
	animation = fadeOut, 1, 5, outBezier
	animation = fadeSwitch, 1, 5, inBezier
	animation = fadeDim, 1, 5, inBezier
	animation = fadeLayersIn, 1, 5, inBezier
	animation = fadeLayersOut, 1, 5, outBezier
	animation = fadePopupsIn, 1, 5, inBezier
	animation = fadePopupsOut, 1, 5, outBezier
	animation = fadeDpms, 1, 5, outBezier

	animation = border, 1, 5, outBezier
	animation = borderangle, 1, 50, outBezier, loop

	animation = workspacesIn, 1, 10, inBezier, slidefade
	animation = workspacesOut, 1, 10, outBezier, slidefade
	animation = specialWorkspaceIn, 1, 10, inBezier, slidefadevert
	animation = specialWorkspaceOut, 1, 10, outBezier, slidefadevert

	animation = zoomFactor, 1, 3, inBezier
	animation = monitorAdded, 1, 10, inBezier
}
